# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tutorial_002' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  # Pods for Tutorial_002

end
